<?php namespace App\Entities;

/**
 * Eloquent class to describe the consultants table
 *
 * automatically generated by ModelGenerator.php
 */
class Consultant extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'consultants';

    protected $fillable = array('phone', 'address', 'photo');

    public function user()
    {
        return $this->belongsTo('App\Entities\User', 'user_id', 'id');
    }

    public function clients()
    {
        return $this->hasMany('App\Entities\Client', 'consultant_id', 'id');
    }
}
