<?php namespace App;

/**
 * Eloquent class to describe the catalogue_product table
 *
 * automatically generated by ModelGenerator.php
 */
class CatalogueProduct extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'catalogue_product';

    public $timestamps = false;

    protected $fillable = array('code', 'value', 'status');

    public function catalogues()
    {
        return $this->belongsTo('App\Catalogues', 'catalogue_id', 'id');
    }

    public function products()
    {
        return $this->belongsTo('App\Products', 'product_id', 'id');
    }
}
