<?php namespace App;

/**
 * Eloquent class to describe the catalogues table
 *
 * automatically generated by ModelGenerator.php
 */
class Catalogues extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'catalogues';

    public function getDates()
    {
        return array('date_expiration', 'date_rescue');
    }

    protected $fillable = array('name', 'code_catalogue', 'date_expiration', 'date_rescue');

    public function consultants()
    {
        return $this->belongsTo('App\Consultants', 'consultant_id', 'id');
    }

    public function catalogueProduct()
    {
        return $this->hasMany('App\CatalogueProduct', 'catalogue_id', 'id');
    }
}
