<?php namespace App;

/**
 * Eloquent class to describe the clients table
 *
 * automatically generated by ModelGenerator.php
 */
class Clients extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'clients';

    protected $fillable = array('name', 'email', 'phone', 'address', 'observation', 'photo');

    public function consultants()
    {
        return $this->belongsTo('App\Consultants', 'consultant_id', 'id');
    }
}
