<?php namespace App;

/**
 * Eloquent class to describe the consultants table
 *
 * automatically generated by ModelGenerator.php
 */
class Consultants extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'consultants';

    protected $fillable = array('phone', 'address', 'photo');

    public function users()
    {
        return $this->belongsTo('App\Users', 'user_id', 'id');
    }

    public function catalogues()
    {
        return $this->hasMany('App\Catalogues', 'consultant_id', 'id');
    }

    public function clients()
    {
        return $this->hasMany('App\Clients', 'consultant_id', 'id');
    }

    public function products()
    {
        return $this->hasMany('App\Products', 'consultant_id', 'id');
    }
}
