<?php namespace App;

/**
 * Eloquent class to describe the oauth_refresh_tokens table
 *
 * automatically generated by ModelGenerator.php
 */
class OauthRefreshTokens extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'oauth_refresh_tokens';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('expires_at');
    }

    protected $fillable = array('access_token_id', 'revoked', 'expires_at');


}
