<?php namespace App;

/**
 * Eloquent class to describe the oauth_auth_codes table
 *
 * automatically generated by ModelGenerator.php
 */
class OauthAuthCodes extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'oauth_auth_codes';

    public $timestamps = false;

    public $incrementing = false;

    public function getDates()
    {
        return array('expires_at');
    }

    protected $fillable = array('user_id', 'client_id', 'scopes', 'revoked', 'expires_at');


}
