<?php namespace App;

/**
 * Eloquent class to describe the oauth_personal_access_clients table
 *
 * automatically generated by ModelGenerator.php
 */
class OauthPersonalAccessClients extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'oauth_personal_access_clients';

    protected $fillable = array('client_id');


}
