<?php namespace App;

/**
 * Eloquent class to describe the oauth_access_tokens table
 *
 * automatically generated by ModelGenerator.php
 */
class OauthAccessTokens extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'oauth_access_tokens';

    public $incrementing = false;

    public function getDates()
    {
        return array('expires_at');
    }

    protected $fillable = array('user_id', 'client_id', 'name', 'scopes', 'revoked', 'expires_at');


}
