<?php namespace App;

/**
 * Eloquent class to describe the products table
 *
 * automatically generated by ModelGenerator.php
 */
class Products extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'products';

    protected $fillable = array('name');

    public function consultants()
    {
        return $this->belongsTo('App\Consultants', 'consultant_id', 'id');
    }

    public function catalogueProduct()
    {
        return $this->hasMany('App\CatalogueProduct', 'product_id', 'id');
    }
}
