<?php namespace App;

/**
 * Eloquent class to describe the users table
 *
 * automatically generated by ModelGenerator.php
 */
class Users extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'users';

    protected $fillable = array('name', 'email', 'password', 'remember_token');

    public function consultants()
    {
        return $this->hasMany('App\Consultants', 'user_id', 'id');
    }
}
